<script>
  // ApparatusIllustration — Layer Cake with Gemini-designed animations
  // Layer 1: Static Adobe-traced SVG (577KB) — NEVER modified
  // Layer 2: Animated SVG overlay — flame, steam, shimmer, flow particles, glows
  // Layer 3: CSS-positioned animated overlays — flame shape, drip, gauge jitter
  //
  // Coordinates measured by Gemini Pro from concept art analysis.
  // Animation SVG generated by Gemini Flash + free-tier Gemini suggestions.

  import {
    beanData, selectedBrewer, matchScore, BREWERS
  } from './store.js';

  let { onclick_vessel, onclick_brewer, onclick_cup } = $props();

  let hasBean = $derived(!!$beanData);
  let hasBrewer = $derived(!!$selectedBrewer);
  let isPopulated = $derived(hasBean && hasBrewer);
  let score = $derived($matchScore);
  let brewerInfo = $derived(BREWERS.find(b => b.id === $selectedBrewer));
  let hoveredZone = $state(null);

  let spokeUrl = $derived(
    hasBean && $beanData?.id
      ? `/tools/brew-dial-in/${$beanData.id}/${hasBrewer ? '?brewer=' + $selectedBrewer : ''}`
      : null
  );
</script>

<div class="apparatus-illustration">
  <div class="apparatus-container">
    <!-- Layer 1: Static background -->
    <img
      src="/assets/brew-dial-in/apparatus-bg.svg"
      alt="The Extraction Apparatus — an interactive coffee brewing laboratory"
      class="apparatus-bg"
      width="1408" height="768"
    />

    <!-- Layer 2: SMIL animated SVG overlay (Gemini-generated coordinates) -->
    <svg viewBox="0 0 1408 768" class="apparatus-overlay" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
          <feGaussianBlur stdDeviation="3" result="blur" />
          <feComposite in="SourceGraphic" in2="blur" operator="over" />
        </filter>
        <filter id="softGlow" x="-50%" y="-50%" width="200%" height="200%">
          <feGaussianBlur stdDeviation="8" result="blur" />
        </filter>
        <radialGradient id="shimmerGrad">
          <stop offset="0%" stop-color="white" stop-opacity="0.8" />
          <stop offset="100%" stop-color="white" stop-opacity="0" />
        </radialGradient>
        <radialGradient id="flameYellow">
          <stop offset="0%" stop-color="#FFFAD5" />
          <stop offset="100%" stop-color="#FFD700" />
        </radialGradient>
        <path id="pipePath" d="M300 415 L400 415 L500 520 L600 570 L700 570 L741 600 L800 530 L900 450 L1000 420 L1100 400" fill="none" />
      </defs>

      <!-- Title warm underglow (breathing radiance behind the nameplate) -->
      <!-- Title banner approximately x=420 to x=990, y=30 to y=65 -->
      <ellipse cx="705" cy="58" rx="300" ry="28" fill="#D4A847" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0;0.4;0" dur="5s" repeatCount="indefinite" />
        <animate attributeName="ry" values="26;32;26" dur="5s" repeatCount="indefinite" />
      </ellipse>

      <!-- Section hover glows -->
      {#if hoveredZone === 'vessel'}
        <rect x="50" y="75" width="240" height="560" rx="20"
          fill="#C17A3A" opacity="0.06" filter="url(#softGlow)" />
      {/if}
      {#if hoveredZone === 'brewer'}
        <rect x="320" y="75" width="380" height="560" rx="20"
          fill="#C17A3A" opacity="0.06" filter="url(#softGlow)" />
      {/if}
      {#if hoveredZone === 'cup'}
        <rect x="890" y="75" width="480" height="560" rx="20"
          fill="#C17A3A" opacity="0.06" filter="url(#softGlow)" />
      {/if}

      <!-- Warm ambient glows (always running) -->
      <circle cx="1150" cy="430" r="70" fill="#C17A3A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.03;0.08;0.03" dur="4s" repeatCount="indefinite" />
      </circle>
      <circle cx="741" cy="600" r="50" fill="#E8834A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.04;0.10;0.04" dur="3s" repeatCount="indefinite" />
      </circle>

      <!-- Spirit lamp warm glow (the CSS flame overlay handles the visible flame) -->
      <!-- Rising sparks from the lamp -->
      <circle r="1.5" fill="#FFD700">
        <animate attributeName="cx" values="741;735;730" dur="2s" repeatCount="indefinite" />
        <animate attributeName="cy" values="610;580;550" dur="2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="1;0.8;0" dur="2s" repeatCount="indefinite" />
      </circle>
      <circle r="1" fill="#FFF">
        <animate attributeName="cx" values="741;745;750" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="610;570;540" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="1;0.7;0" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
      </circle>

      <!-- Siphon flask bubbles (inside the water in lower half of globe) -->
      <circle r="3" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="730;733;728" dur="2.5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="570;545;510" dur="2.5s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;3.5;4" dur="2.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.5;0" dur="2.5s" repeatCount="indefinite" />
      </circle>
      <circle r="2" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="745;740;748" dur="3s" begin="0.8s" repeatCount="indefinite" />
        <animate attributeName="cy" values="575;550;515" dur="3s" begin="0.8s" repeatCount="indefinite" />
        <animate attributeName="r" values="1.5;3;3.5" dur="3s" begin="0.8s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.45;0" dur="3s" begin="0.8s" repeatCount="indefinite" />
      </circle>
      <circle r="2.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="755;750;758" dur="2.8s" begin="1.5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="572;548;518" dur="2.8s" begin="1.5s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;3;4.5" dur="2.8s" begin="1.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.5;0" dur="2.8s" begin="1.5s" repeatCount="indefinite" />
      </circle>
      <circle r="1.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="738;742;735" dur="3.5s" begin="0.3s" repeatCount="indefinite" />
        <animate attributeName="cy" values="568;540;508" dur="3.5s" begin="0.3s" repeatCount="indefinite" />
        <animate attributeName="r" values="1;2.5;3" dur="3.5s" begin="0.3s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.4;0" dur="3.5s" begin="0.3s" repeatCount="indefinite" />
      </circle>
      <circle r="2" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="725;730;722" dur="2.2s" begin="2s" repeatCount="indefinite" />
        <animate attributeName="cy" values="575;552;520" dur="2.2s" begin="2s" repeatCount="indefinite" />
        <animate attributeName="r" values="1.5;2.5;3.5" dur="2.2s" begin="2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.5;0" dur="2.2s" begin="2s" repeatCount="indefinite" />
      </circle>
      <circle r="3" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="750;745;753" dur="4s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="cy" values="573;548;512" dur="4s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;4;5" dur="4s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.35;0" dur="4s" begin="1s" repeatCount="indefinite" />
      </circle>
      <!-- Left side bubbles -->
      <circle r="2" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="705;708;703" dur="2.8s" begin="0.4s" repeatCount="indefinite" />
        <animate attributeName="cy" values="572;548;515" dur="2.8s" begin="0.4s" repeatCount="indefinite" />
        <animate attributeName="r" values="1.5;3;3.5" dur="2.8s" begin="0.4s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.45;0" dur="2.8s" begin="0.4s" repeatCount="indefinite" />
      </circle>
      <circle r="2.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="712;715;710" dur="3.2s" begin="1.8s" repeatCount="indefinite" />
        <animate attributeName="cy" values="575;550;518" dur="3.2s" begin="1.8s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;3.5;4" dur="3.2s" begin="1.8s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.5;0" dur="3.2s" begin="1.8s" repeatCount="indefinite" />
      </circle>
      <circle r="1.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="698;702;696" dur="2.4s" begin="2.5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="568;545;512" dur="2.4s" begin="2.5s" repeatCount="indefinite" />
        <animate attributeName="r" values="1;2;3" dur="2.4s" begin="2.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.4;0" dur="2.4s" begin="2.5s" repeatCount="indefinite" />
      </circle>
      <!-- Right side bubbles -->
      <circle r="2.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="770;773;768" dur="3s" begin="0.6s" repeatCount="indefinite" />
        <animate attributeName="cy" values="574;548;514" dur="3s" begin="0.6s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;3.5;4.5" dur="3s" begin="0.6s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.5;0" dur="3s" begin="0.6s" repeatCount="indefinite" />
      </circle>
      <circle r="2" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="778;775;780" dur="2.6s" begin="1.3s" repeatCount="indefinite" />
        <animate attributeName="cy" values="570;545;510" dur="2.6s" begin="1.3s" repeatCount="indefinite" />
        <animate attributeName="r" values="1.5;2.5;3.5" dur="2.6s" begin="1.3s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.45;0" dur="2.6s" begin="1.3s" repeatCount="indefinite" />
      </circle>
      <circle r="1.5" fill="none" stroke="rgba(100,90,70,0.9)" stroke-width="1.5">
        <animate attributeName="cx" values="765;768;762" dur="3.5s" begin="2.2s" repeatCount="indefinite" />
        <animate attributeName="cy" values="573;552;520" dur="3.5s" begin="2.2s" repeatCount="indefinite" />
        <animate attributeName="r" values="1;2.5;3" dur="3.5s" begin="2.2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.4;0" dur="3.5s" begin="2.2s" repeatCount="indefinite" />
      </circle>

      <!-- Cup steam wisps (rising from cup rim at ~1150, 525) -->
      <g opacity="0.5" stroke="rgba(140,130,115,0.7)" stroke-width="3.5" fill="none" stroke-linecap="round">
        <path d="M1110 525 C 1095 500, 1115 480, 1100 458">
          <animate attributeName="stroke-dasharray" values="0,100;100,0" dur="3s" repeatCount="indefinite" />
          <animate attributeName="stroke-dashoffset" values="0;-100" dur="3s" repeatCount="indefinite" />
          <animate attributeName="opacity" values="0;0.8;0" dur="3s" repeatCount="indefinite" />
        </path>
        <path d="M1145 525 C 1155 498, 1135 478, 1150 455">
          <animate attributeName="stroke-dasharray" values="0,100;100,0" dur="4s" begin="1s" repeatCount="indefinite" />
          <animate attributeName="stroke-dashoffset" values="0;-100" dur="4s" begin="1s" repeatCount="indefinite" />
          <animate attributeName="opacity" values="0;0.8;0" dur="4s" begin="1s" repeatCount="indefinite" />
        </path>
        <path d="M1175 525 C 1190 498, 1170 480, 1185 458">
          <animate attributeName="stroke-dasharray" values="0,100;100,0" dur="3.5s" begin="0.5s" repeatCount="indefinite" />
          <animate attributeName="stroke-dashoffset" values="0;-100" dur="3.5s" begin="0.5s" repeatCount="indefinite" />
          <animate attributeName="opacity" values="0;0.8;0" dur="3.5s" begin="0.5s" repeatCount="indefinite" />
        </path>
        <path d="M1130 525 C 1120 502, 1145 485, 1125 460">
          <animate attributeName="stroke-dasharray" values="0,100;100,0" dur="5s" begin="2s" repeatCount="indefinite" />
          <animate attributeName="stroke-dashoffset" values="0;-100" dur="5s" begin="2s" repeatCount="indefinite" />
          <animate attributeName="opacity" values="0;0.8;0" dur="5s" begin="2s" repeatCount="indefinite" />
        </path>
      </g>

      <!-- Porthole shimmer (sweeping across glass at ~313, 430) -->
      <ellipse rx="18" ry="12" fill="url(#shimmerGrad)">
        <animate attributeName="cx" values="285;340;285" dur="5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="415;445;415" dur="4s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.3;0.55;0.3" dur="2.5s" repeatCount="indefinite" />
      </ellipse>

      <!-- Porthole warm inner glow (amber light from within, beans radiating warmth) -->
      <!-- Porthole center approximately (200, 400) -->
      <circle cx="315" cy="420" r="45" fill="#D4A847" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.08;0.22;0.08" dur="3.5s" repeatCount="indefinite" />
        <animate attributeName="r" values="42;50;42" dur="3.5s" repeatCount="indefinite" />
      </circle>
      <!-- Lens flare on porthole glass centered at (315, 435) -->
      <!-- Outer soft glow (large diffused warm light) -->
      <circle cx="315" cy="435" r="45" fill="#FFD700" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.06;0.2;0.06" dur="5s" repeatCount="indefinite" />
      </circle>
      <!-- Hot center spot -->
      <circle cx="315" cy="435" r="6" fill="white" filter="url(#glow)">
        <animate attributeName="opacity" values="0.15;0.6;0.15" dur="5s" repeatCount="indefinite" />
        <animate attributeName="r" values="4;7;4" dur="5s" repeatCount="indefinite" />
      </circle>
      <!-- Horizontal streak (the main flare line) -->
      <line x1="265" y1="435" x2="365" y2="435" stroke="white" stroke-width="1.5" stroke-linecap="round" filter="url(#glow)">
        <animate attributeName="opacity" values="0.05;0.35;0.05" dur="5s" repeatCount="indefinite" />
      </line>
      <!-- Secondary reflection spots (smaller circles offset along horizontal) -->
      <circle cx="345" cy="435" r="3" fill="#FFD700" filter="url(#glow)">
        <animate attributeName="opacity" values="0;0.25;0" dur="5s" begin="0.3s" repeatCount="indefinite" />
      </circle>
      <circle cx="280" cy="435" r="2.5" fill="#FFE0A0" filter="url(#glow)">
        <animate attributeName="opacity" values="0;0.2;0" dur="5s" begin="0.6s" repeatCount="indefinite" />
      </circle>

      <!-- V60 steam removed — the instrument should look ready, not mid-brew -->

      <!-- Match score gauge needle jitter (tremor at ~1270, 570) -->
      <!-- Gauge center approximately (1270, 570), needle as a short line -->
      <line x1="1270" y1="570" x2="1270" y2="545" stroke="#2c2c2c" stroke-width="2" stroke-linecap="round">
        <animateTransform attributeName="transform" type="rotate"
          values="42,1270,570;44,1270,570;41,1270,570;43,1270,570;42,1270,570"
          dur="0.8s" repeatCount="indefinite" />
      </line>
      <circle cx="1270" cy="570" r="3" fill="#2c2c2c" />

      <!-- Pipe junction warm spots (glowing dots at connection/valve points) -->
      <!-- Vessel outlet -->
      <circle cx="305" cy="415" r="8" fill="#E8834A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.06;0.2;0.06" dur="2.5s" repeatCount="indefinite" />
      </circle>
      <!-- Brewer inlet (left pipe junction) -->
      <circle cx="560" cy="310" r="7" fill="#E8834A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.06;0.18;0.06" dur="3s" begin="0.5s" repeatCount="indefinite" />
      </circle>
      <!-- Brewer to gauges junction -->
      <circle cx="820" cy="420" r="7" fill="#E8834A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.06;0.18;0.06" dur="2.8s" begin="1s" repeatCount="indefinite" />
      </circle>
      <!-- Cup inlet pipe junction -->
      <circle cx="1050" cy="380" r="7" fill="#E8834A" filter="url(#softGlow)">
        <animate attributeName="opacity" values="0.06;0.18;0.06" dur="3.2s" begin="1.5s" repeatCount="indefinite" />
      </circle>

      <!-- V60 drip stream (drops falling through neck into flask) -->
      <!-- Neck center at approximately (742, 420), drops fall into flask at (742, 490) -->
      <circle r="2.5" fill="rgba(101,67,33,0.6)">
        <animate attributeName="cx" values="742;743;741" dur="1.2s" repeatCount="indefinite" />
        <animate attributeName="cy" values="455;478;510" dur="1.2s" repeatCount="indefinite" />
        <animate attributeName="r" values="2;2.5;1.5" dur="1.2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.7;0.5;0" dur="1.2s" repeatCount="indefinite" />
      </circle>
      <circle r="2" fill="rgba(101,67,33,0.6)">
        <animate attributeName="cx" values="744;742;745" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="cy" values="455;480;510" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="r" values="1.5;2.5;1" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.6;0.5;0" dur="1.5s" begin="0.5s" repeatCount="indefinite" />
      </circle>
      <circle r="1.5" fill="rgba(101,67,33,0.5)">
        <animate attributeName="cx" values="740;741;739" dur="1.8s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="cy" values="457;483;510" dur="1.8s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="r" values="1;2;1.5" dur="1.8s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.5;0.4;0" dur="1.8s" begin="1s" repeatCount="indefinite" />
      </circle>

      <!-- Coffee drip into cup (drop forming at pipe outlet and falling) -->
      <!-- Pipe outlet above cup at approximately (1150, 385), drops fall to cup surface at (1150, 510) -->
      <circle r="3" fill="rgba(79,52,25,0.7)">
        <animate attributeName="cx" values="1150;1150;1152" dur="2s" repeatCount="indefinite" />
        <animate attributeName="cy" values="385;440;510" dur="2s" repeatCount="indefinite" />
        <animate attributeName="r" values="1;3;2" dur="2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.7;0" dur="2s" repeatCount="indefinite" />
      </circle>
      <circle r="2" fill="rgba(79,52,25,0.6)">
        <animate attributeName="cx" values="1152;1150;1148" dur="2.5s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="cy" values="385;445;510" dur="2.5s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="r" values="0.5;2.5;1.5" dur="2.5s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0;0.6;0" dur="2.5s" begin="1s" repeatCount="indefinite" />
      </circle>

      <!-- Cup liquid surface shimmer (ripple/swirl on coffee surface) -->
      <!-- Cup liquid surface at approximately (1150, 545), radius ~60 -->
      <ellipse cx="1150" cy="545" rx="55" ry="8" fill="none"
        stroke="rgba(160,120,80,0.3)" stroke-width="1.5">
        <animate attributeName="rx" values="50;58;50" dur="3s" repeatCount="indefinite" />
        <animate attributeName="ry" values="7;9;7" dur="2s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.15;0.35;0.15" dur="3s" repeatCount="indefinite" />
      </ellipse>
      <ellipse cx="1150" cy="545" rx="35" ry="5" fill="none"
        stroke="rgba(160,120,80,0.25)" stroke-width="1">
        <animate attributeName="rx" values="38;30;38" dur="4s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="ry" values="6;4;6" dur="3s" begin="1s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.1;0.3;0.1" dur="4s" begin="1s" repeatCount="indefinite" />
      </ellipse>
      <ellipse cx="1150" cy="543" rx="20" ry="3" fill="none"
        stroke="rgba(180,140,100,0.2)" stroke-width="0.8">
        <animate attributeName="rx" values="22;16;22" dur="2.5s" begin="0.5s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.1;0.25;0.1" dur="2.5s" begin="0.5s" repeatCount="indefinite" />
      </ellipse>

      <!-- Click zones — cover machine components + text, no gaps -->
      <!-- Zone I: Bean vessel + annotations (left third) -->
      <rect x="20" y="60" width="310" height="600" rx="4"
        fill="transparent" class="click-zone"
        onclick={onclick_vessel}
        onmouseenter={() => hoveredZone = 'vessel'}
        onmouseleave={() => hoveredZone = null}
      >
        <title>{hasBean ? 'Change bean' : 'Click to select a bean'}</title>
      </rect>
      <!-- Zone II: Brewer + V60 + siphon + lamp + annotations (center third) -->
      <rect x="330" y="60" width="470" height="600" rx="4"
        fill="transparent" class="click-zone"
        onclick={onclick_brewer}
        onmouseenter={() => hoveredZone = 'brewer'}
        onmouseleave={() => hoveredZone = null}
      >
        <title>{hasBrewer ? 'Change brewer' : 'Click to select a brewer'}</title>
      </rect>
      <!-- Zone III: Cup + gauges + notes + match score (right third) -->
      <rect x="800" y="60" width="590" height="600" rx="4"
        fill="transparent" class="click-zone"
        onclick={onclick_cup}
        onmouseenter={() => hoveredZone = 'cup'}
        onmouseleave={() => hoveredZone = null}
      >
        <title>View flavor profile</title>
      </rect>

      {#if !hasBean && !hoveredZone}
        <text x="704" y="730" text-anchor="middle"
          font-family="'Inter', sans-serif" font-size="16" fill="#8B5E2B"
          font-style="italic" opacity="0.5">
          Click the vessel, brewer, or cup to begin
        </text>
      {/if}
    </svg>

    <!-- Layer 3: CSS-animated flame overlay (free-tier Gemini design) -->
    <svg class="anim-flame" viewBox="0 0 50 50">
      <path class="flame-outer" d="M25,50 C25,50 10,35 15,20 C18,10 25,0 25,0 C25,0 32,10 35,20 C40,35 25,50 25,50 Z"/>
      <path class="flame-inner" d="M25,50 C25,50 15,40 18,30 C20,20 25,15 25,15 C25,15 30,20 32,30 C35,40 25,50 25,50 Z"/>
    </svg>

    <!-- Drip removed — needs exact pipe outlet position -->
  </div>

  <!-- Floating result card -->
  {#if isPopulated && spokeUrl}
    <div class="result-card">
      <div class="result-content">
        <div class="result-bean">
          <span class="result-name">{$beanData.name}</span>
          <span class="result-by">by {$beanData.roaster}</span>
        </div>
        <div class="result-brewer">
          <span class="result-method">{brewerInfo?.name}</span>
          <span class="result-score" style="color: {score >= 85 ? '#4ADE80' : score >= 70 ? '#C17A3A' : '#FBBF24'}">{score}/100</span>
        </div>
        <a href={spokeUrl} class="result-cta">View Brewing Guide &rarr;</a>
      </div>
    </div>
  {/if}
</div>

<style>
  .apparatus-illustration {
    width: 100%;
    max-width: 1100px;
    margin: 0 auto;
  }
  .apparatus-container {
    position: relative;
    width: 100%;
    aspect-ratio: 1408 / 768;
  }
  .apparatus-bg {
    width: 100%;
    height: 100%;
    display: block;
    object-fit: contain;
  }
  .apparatus-overlay {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
  }

  /* Click zones */
  .click-zone {
    cursor: pointer;
    outline: none;
    -webkit-tap-highlight-color: transparent;
  }

  /* CSS flame overlay (positioned on lamp) */
  .anim-flame {
    position: absolute;
    top: 75.6%;
    left: 52.75%;
    width: 3.2%;
    pointer-events: none;
    transform: translateX(-50%);
  }
  .flame-outer {
    fill: #ff9900;
    transform-origin: bottom center;
    animation: flicker 0.15s ease-in-out infinite alternate;
    opacity: 0.75;
  }
  .flame-inner {
    fill: #ffcc00;
    transform-origin: bottom center;
    animation: flickerInner 0.2s ease-in-out infinite alternate;
    opacity: 0.9;
  }
  @keyframes flicker {
    0% { transform: scale(1, 1) translateY(0); opacity: 0.7; }
    100% { transform: scale(1.05, 1.1) translateY(-1px); opacity: 0.9; }
  }
  @keyframes flickerInner {
    0% { transform: scale(1, 1); }
    100% { transform: scale(0.9, 1.2); }
  }

  /* CSS drip overlay */
  .anim-drip {
    position: absolute;
    top: 52%;
    left: 78%;
    width: 1.5%;
    pointer-events: none;
  }
  .drop {
    fill: #4b3621;
    animation: drip 2s infinite;
  }
  @keyframes drip {
    0% { transform: translateY(0) scale(0); opacity: 1; }
    20% { transform: translateY(10px) scale(1); opacity: 1; }
    80% { transform: translateY(80px) scale(1); opacity: 0; }
    100% { transform: translateY(80px) scale(0); opacity: 0; }
  }

  /* Result card */
  .result-card {
    margin-top: 1rem;
    display: flex;
    justify-content: center;
    animation: slideUp 0.4s ease-out;
  }
  @keyframes slideUp {
    from { opacity: 0; transform: translateY(12px); }
    to { opacity: 1; transform: translateY(0); }
  }
  .result-content {
    display: flex;
    align-items: center;
    gap: 1.5rem;
    background: white;
    border: 1.5px solid #D4C5A9;
    border-left: 4px solid #C17A3A;
    border-radius: 4px;
    padding: 0.75rem 1.25rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.06);
  }
  .result-bean { display: flex; flex-direction: column; }
  .result-name { font-family: 'Playfair Display', serif; font-size: 1.05rem; font-weight: 700; color: #1A1A1A; }
  .result-by { font-family: 'Inter', sans-serif; font-size: 0.75rem; color: #94A3B8; }
  .result-brewer {
    display: flex; flex-direction: column; align-items: center;
    padding: 0 1rem;
    border-left: 1px solid #E5E0D8;
    border-right: 1px solid #E5E0D8;
  }
  .result-method { font-family: 'Inter', sans-serif; font-size: 0.8rem; font-weight: 600; color: #1A1A1A; }
  .result-score { font-family: 'Inter', sans-serif; font-size: 1.1rem; font-weight: 800; }
  .result-cta {
    font-family: 'Inter', sans-serif; font-size: 0.85rem; font-weight: 600;
    color: white; background: #C17A3A; padding: 0.5rem 1.25rem;
    border-radius: 3px; text-decoration: none; white-space: nowrap;
    transition: background 0.2s;
  }
  .result-cta:hover { background: #A86830; }

  @media (max-width: 768px) {
    .apparatus-illustration { overflow-x: auto; -webkit-overflow-scrolling: touch; }
    .apparatus-container { min-width: 700px; }
    .result-content { flex-direction: column; gap: 0.75rem; text-align: center; }
    .result-brewer {
      border-left: none; border-right: none;
      border-top: 1px solid #E5E0D8; border-bottom: 1px solid #E5E0D8;
      padding: 0.5rem 0; flex-direction: row; gap: 0.75rem;
    }
  }
</style>
